config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  resources :posts do
    resources :comments
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :circles
  resources :trouble_bords, only: %i[index create show destroy] do
    resources :bord_comments, only: %i[create edit update destroy]
  end
  resources :favorite_posts, only: %i[create destroy]
  resources :favorite_users, only: %i[create destroy]
  resources :circle_members, only: %i[create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bord_comment.rb
class BordComment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :trouble_bord
end

app/models/circle.rb
class Circle < ApplicationRecord
  validates :circle_name, presence: true
  has_many :circle_members, dependent: :destroy
  has_many :user, through: :circle_members
  mount_uploader :circle_image, ImageUploader
end

app/models/circle_member.rb
class CircleMember < ApplicationRecord
  belongs_to :user
  belongs_to :circle
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite_user.rb
class FavoriteUser < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorite_posts, dependent: :destroy
  has_many :followers, through: :favorite_posts, source: :user
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: :user
  mount_uploader :image, ImageUploader
end

app/models/trouble_bord.rb
class TroubleBord < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  has_many :bord_comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 } , on: :create
  before_save { email.downcase! }

  has_many :posts, dependent: :destroy
  has_many :trouble_bords, dependent: :destroy
  has_many :bord_comments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :circles, dependent: :destroy

  has_many :favorite_posts, dependent: :destroy
  has_many :favorite_another_posts, through: :favorite_posts, source: :post

  has_many :circle_members, dependent: :destroy
  has_many :favorite_circles, through: :circle_members, source: :circle

  has_many :active_favorite_users, foreign_key: 'follower_id',
            class_name: 'FavoriteUser', dependent: :destroy
  has_many :passive_favorite_users, foreign_key: 'followed_id',
            class_name: 'FavoriteUser', dependent: :destroy
  has_many :following, through: :active_favorite_users, source: :followed
  has_many :followers, through: :passive_favorite_users, source: :follower
  mount_uploader :image, ImageUploader

  def follow!(other_user)
    active_favorite_users.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_favorite_users.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_favorite_users.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :force_top

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post.id), notice: '日記を作成しました'
      unless @post.user.followers.blank?
        NoticeMailer.notice_mail(@post).deliver
      end
    else
      render 'new'
    end
  end

  def show
    @favorite_post = current_user.favorite_posts.find_by(post_id: @post.id)
    @comment = @post.comments.build
    @comments = @post.comments.order(created_at: :asc)
  end

  def index
    @search = Post.search(params[:q])
    @search_posts = @search.result.includes(:user).page(params[:page])

    current_user_id = params[:id]

    if current_user_id.nil?
      if @search_posts.nil?
        @posts = Post.page(params[:page])
      else
        @posts = @search_posts
      end
    else
      @posts = Post.where(user_id: current_user_id).page(params[:page])
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: '日記を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(current_user.id), notice: 'ブログを削除しました！'
  end
  private
  def post_params
    params.require(:post).permit(:title, :content, :image,:image_cache)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :force_top, only: :show
  before_action :set_user, only: %i[show edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: 'ユーザー登録完了しました'
    else
      render 'new'
    end
  end

  def show
    @posts = @user.posts.limit(5).order('id DESC')
    @born_from = Time.zone.today - @user.birthday
  end

  def edit; end

  def update
    if @user.update(user_edit_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'ユーザー情報を削除しました'
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :email, :password, :child_name, :comment, :birthday,
      :image, :image_cache
    )
  end

  def user_edit_params
    params.require(:user).permit(
      :name, :email, :child_name, :comment, :birthday, :image, :image_cache
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/bord_comments_helper.rb
module BordCommentsHelper
end

app/helpers/circle_members_helper.rb
module CircleMembersHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_posts_helper.rb
module FavoritePostsHelper
end

app/helpers/favorite_users_helper.rb
module FavoriteUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/trouble_bords_helper.rb
module TroubleBordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="mb-5">
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %></h2>
      <ul class="list-unstyled">
        <% @post.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<%= form_with(model: @post, local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :title, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.text_field :title, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :content, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.text_field :content, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :image, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.file_field :image, class: "form-control-file" %></div>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group row">
    <div class="offset-2 pl-3">
      <%= f.submit "登録する" %>
    </div>
  </div>
<% end %>
<%= link_to "マイページに戻る", user_path(current_user.id), class: "btn btn-primary btn-lg rounded-pill mb-5" %>

app/views/posts/edit.html.erb
<div class="container text-center text-primary">
  <h2>日記編集</h2>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<section class="portfolio bg-secondary" id="portfolio">
  <div class="container">
    <h2 class="text-center text-primary mb-0">日記一覧</h2>
    <%= search_form_for @search do |f| %>
      <div class="input-group">
        <!-- <%= f.label :title_or_content_or_user_name_cont, "検索" %> -->
        <%= f.text_field :title_or_content_or_user_name_cont, class: "form-controll", placeholder: "キーワード検索" %>
          <div class="input-group-btn">
            <%= button_tag '<i class="fa fa-search"></i>検索'.html_safe, type: "submit", class: "btn btn-default btn-s-md" %>
            <!-- <%= f.submit button:"btn btn-default" %> -->
          </div>
      </div>
    <% end %>
    <div>
      <!-- <%= page_entries_info @posts %> -->
      <% if @search_posts.empty? %>
        <div class="m-5 text-center"><h1><%= "検索結果はありませんでした" %></h1></div>
        <div class="text-center"><%= link_to "日記一覧を表示する", posts_path %></div>
      <% end %>
    </div>

    <div class="row">
      <% @posts.each do |post| %>
      <div class="col-md-6 col-lg-4">
        <!-- <%= post.title %> -->
        <%= link_to post_path(post.id) do %>
        <div class="post-grid">
          <p>タイトル：<%= post.title %></p>
          <p>投稿者：<%= post.user.name %></p>
          <p><%= image_tag post.image %></p>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</section>

app/views/posts/new.html.erb
<div class="container text-center text-primary">
  <h2>日記新規作成</h2>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="portfolio-modal">
  <div class="portfolio-modal-dialog bg-secondary">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-primary mb-2">
            <%= @post.title %>
          </h2>
          <%= image_tag @post.image,class: "img-fluid mb-5" %>
          <p class="mb-5"><%= @post.content %></p>
          <p class="mb-5">By <%= link_to @post.user.name, user_path(@post.user.id) %></p>
        </div>
      </div>

      <div>
        <% if @post.user_id == current_user.id %>
          <%= link_to "編集する", edit_post_path(@post.id),class: "btn btn-primary btn-lg rounded-pill" %>
          <%= link_to "削除する", post_path(@post.id), method: :delete, data: { confirm: '本当に削除していいですか？' },class: "btn btn-danger btn-lg rounded-pill" %>
        <% else %>
          <% if @favorite_post.present? %>
          <%= link_to "いいね！！解除", favorite_post_path(id: @favorite_post.id,
              post_id: @post.id),method: :delete,class:  "btn btn-danger btn-lg rounded-pill" %>
          <% else %>
            <%= link_to "いいね！！", favorite_posts_path(post_id: @post.id), method: :post,class:  "btn btn-info btn-lg rounded-pill" %>
          <% end %>
        <% end %>
          <hr class="star-dark">
      </div>
      <p>コメント一覧</p>
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, post: @post} %>
      </div>
      <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="mb-5 list-unstyled">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %></h2>
      <ul class="list-unstyled">
        <% @user.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<%= form_with(model: @user,local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.text_field :name, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.text_field :email, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :child_name, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.text_field :child_name, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :birthday, class:"cotrol-label col-2" %>
    <div class="col-8 text-left"><%= f.date_select :birthday, class: "custom-select" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :image, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.file_field :image , id: :user_image, class: "form-control-file" %></div>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group row">
    <%= f.label :comment, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.text_area :comment, class: "form-control" %></div>
  </div>
  <div class="form-group row" id="passwd_form">
    <%= f.label :password, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.password_field :password, class: "form-control" %></div>
  </div>
  <div class="form-group row" id="passwd_form">
    <%= f.label :password_confirmation, class:"cotrol-label col-2" %>
    <div class="col-8"><%= f.password_field :password_confirmation, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <div class="offset-2 pl-3">
      <%= f.submit "登録します" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container text-center text-primary justify-content-center">
  <h2>ユーザー情報編集画面</h2>
  <div class="mb-5 list-unstyled">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %></h2>
        <ul class="list-unstyled">
          <% @user.errors.full_messages.each do |m| %>
            <li><%= m %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= form_with(model: @user,local: true) do |f| %>
    <div class="form-group row">
      <%= f.label :name, class:"cotrol-label col-2" %>
      <div class="col-8"><%= f.text_field :name, class: "form-control" %></div>
    </div>
    <div class="form-group row">
      <%= f.label :email, class:"cotrol-label col-2" %>
      <div class="col-8"><%= f.text_field :email, class: "form-control" %></div>
    </div>
    <div class="form-group row">
      <%= f.label :child_name, class:"cotrol-label col-2" %>
      <div class="col-8"><%= f.text_field :child_name, class: "form-control" %></div>
    </div>
    <div class="form-group row">
      <%= f.label :birthday, class:"cotrol-label col-2" %>
      <div class="col-8 text-left"><%= f.date_select :birthday, class: "custom-select" %></div>
    </div>
    <div class="form-group row">
      <%= f.label :image, class:"cotrol-label col-2" %>
      <div class="col-8"><%= f.file_field :image , id: :user_image, class: "form-control-file" %></div>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="form-group row">
      <%= f.label :comment, class:"cotrol-label col-2" %>
      <div class="col-8"><%= f.text_area :comment, class: "form-control" %></div>
    </div>
    <div class="form-group row">
      <div class="offset-2 pl-3">
        <%= f.submit "登録します" %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="container text-center text-primary justify-content-center">
  <h2>新規ユーザー登録画面</h2>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="portfolio-modal">
  <div class="portfolio-modal-dialog bg-secondary">
    <div class="container text-center justify-content-center">
      <h2 class="text-primary">ユーザー情報</h2>
      <div class="row text-primary">
        <div class="col-6 text-left profile">
          <div class="row mb-3">
            <p class="col-lg-4 mb-1">おなまえ:</p>
            <p class="col-lg-8 text-left mb-1"><%= @user.name %>さん</p>
          </div>
          <div class="row mb-3">
            <p class="col-lg-4 mb-1">お子さん:</p>
            <p class="col-lg-8 text-left mb-1"><%= @user.child_name %>ちゃん</p>
          </div>
          <p>誕生日から<%= @born_from.to_i %>日目</p>
          <% if current_user.id == @user.id %>
            <p><%= link_to "ユーザー情報の編集", edit_user_path(@user), class: "btn btn-primary btn-block btn-font rounded-pill mb-2"  %></p>
            <p><%= link_to "ユーザー情報を削除", user_path(@user), method: :delete, class: "btn btn-danger btn-block btn-font rounded-pill mb-2", data: { confirm: '本当に削除していいですか？' } %></p>
          <% end %>
        </div>
        <div class="col-4 align-self-center mr-3">
          <%= image_tag @user.image,class: "rounded-circle" %>
        </div>
      </div>
      <div>
        <% unless current_user.id == @user.id %>
          <% unless current_user.following?(@user) %>
            <%= form_with(model: current_user.active_favorite_users.new(followed_id: @user.id)) do |f| %>
              <%= f.hidden_field :followed_id %>
              <%= f.submit "このユーザーとお友達になる" %>
            <% end %>
          <% else %>
            <%= form_with(model: current_user.active_favorite_users.find_by(followed_id: @user.id), method: :delete ) do |f| %>
              <%= f.submit "お友達を解除" %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <hr class="star-dark">
      <div>
        <p>自己紹介</p>
        <%= @user.comment %>
      </div>

      <hr class="star-dark">
      <p>最近の日記一覧</p>
      <div class="mb-4 row justify-content-center">
        <% @posts.each do |post| %>
          <div class="col-8">
          <%= link_to post_path(post.id) do %>
            <div class="post-title mb-3">
              <%= post.title %>
            </div>
          <% end %>
        </div>
        <% end %>
      </div>

      <div>
        <% if current_user.id == @user.id %>
          <%= link_to "日記を作成する", new_post_path, class: "btn btn-primary btn-lg rounded-pill mb-2"  %>
          <%= link_to "自分の日記一覧を見る", posts_path(id: @user.id), class: "btn btn-info btn-lg rounded-pill mb-2" %>
        <% end %>
      </div>

      <hr class="star-dark">
      <p>フォロワー一覧</p>
      <div class="row justify-content-center">
        <% @user.following.each do |user| %>
          <div class="col-8">
            <%= link_to user_path(user.id) do %>
              <div class="post-title mb-3"><%= user.name %></div>
            <% end %>
          </div>
        <% end %>
      </div>

      <hr class="star-dark">
      <div>
        <p>参加サークル一覧</p>
        <div class="mb-4 row justify-content-center">
        <% @user.favorite_circles.each do |circle| %>
        <div class="col-8">
          <%= link_to circle_path(circle.id) do %>
            <div class="post-title mb-3"><%= circle.circle_name %></div>
          <% end %>
        </div>
        <% end %>
      </div>

      <hr class="star-dark">
      <diV>
        <p>お気に入り投稿一覧</p>
        <div class="mb-4 row justify-content-center">
          <% @user.favorite_posts.each do |favorite_post| %>
          <div class="col-8">
            <%= link_to post_path(favorite_post.post.id) do %>
              <div class="post-title mb-3"><%= favorite_post.post.title %></div>
            <% end %>
          </div>
        <% end %>
      </diV>
    </div>
  </div>
</div>