config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  resources :posts do
    resources :comments
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :circles
  resources :trouble_bords, only: %i[index create show destroy] do
    resources :bord_comments, only: %i[create edit update destroy]
  end
  resources :favorite_posts, only: %i[create destroy]
  resources :favorite_users, only: %i[create destroy]
  resources :circle_members, only: %i[create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bord_comment.rb
class BordComment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :trouble_bord
end

app/models/circle.rb
class Circle < ApplicationRecord
  validates :circle_name, presence: true
  has_many :circle_members, dependent: :destroy
  has_many :user, through: :circle_members
  mount_uploader :circle_image, ImageUploader
end

app/models/circle_member.rb
class CircleMember < ApplicationRecord
  belongs_to :user
  belongs_to :circle
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite_user.rb
class FavoriteUser < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorite_posts, dependent: :destroy
  has_many :followers, through: :favorite_posts, source: :user
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: :user
  mount_uploader :image, ImageUploader
end

app/models/trouble_bord.rb
class TroubleBord < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  has_many :bord_comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 } , on: :create
  before_save { email.downcase! }

  has_many :posts, dependent: :destroy
  has_many :trouble_bords, dependent: :destroy
  has_many :bord_comments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :circles, dependent: :destroy

  has_many :favorite_posts, dependent: :destroy
  has_many :favorite_another_posts, through: :favorite_posts, source: :post

  has_many :circle_members, dependent: :destroy
  has_many :favorite_circles, through: :circle_members, source: :circle

  has_many :active_favorite_users, foreign_key: 'follower_id',
            class_name: 'FavoriteUser', dependent: :destroy
  has_many :passive_favorite_users, foreign_key: 'followed_id',
            class_name: 'FavoriteUser', dependent: :destroy
  has_many :following, through: :active_favorite_users, source: :followed
  has_many :followers, through: :passive_favorite_users, source: :follower
  mount_uploader :image, ImageUploader

  def follow!(other_user)
    active_favorite_users.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_favorite_users.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_favorite_users.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :set_circle, only: %i[show edit update destroy]
  before_action :force_top

  def new
    @circle = Circle.new
  end

  def create
    @circle = current_user.circles.build(circle_params)
    if @circle.save
      circlemember = current_user.circle_members.create(circle_id: @circle.id)
      redirect_to circle_path(@circle.id), notice: 'サークルを作成しました'
    else
      render :new
    end
  end

  def show
    @circlemember = current_user.circle_members.find_by(circle_id: @circle.id)
  end

  def edit
  end

  def update
    if @circle.update(circle_params)
      redirect_to circle_path(@circle.id)
    else
      render :edit
    end
  end

  def index
    @search = Circle.search(params[:q])
    @search_circles = @search.result.includes(:user, :circle_members)

    if @search_circles.nil?
      @circles = Circle.all
    else
      @circles = @search_circles
    end
  end

  def destroy
    @circle.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def circle_params
    params.require(:circle).permit(:circle_content,:circle_name,:circle_image)
  end

  def set_circle
    @circle = Circle.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :force_top

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post.id), notice: '日記を作成しました'
      unless @post.user.followers.blank?
        NoticeMailer.notice_mail(@post).deliver
      end
    else
      render 'new'
    end
  end

  def show
    @favorite_post = current_user.favorite_posts.find_by(post_id: @post.id)
    @comment = @post.comments.build
    @comments = @post.comments.order(created_at: :asc)
  end

  def index
    @search = Post.search(params[:q])
    @search_posts = @search.result.includes(:user).page(params[:page])

    current_user_id = params[:id]

    if current_user_id.nil?
      if @search_posts.nil?
        @posts = Post.page(params[:page])
      else
        @posts = @search_posts
      end
    else
      @posts = Post.where(user_id: current_user_id).page(params[:page])
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: '日記を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(current_user.id), notice: 'ブログを削除しました！'
  end
  private
  def post_params
    params.require(:post).permit(:title, :content, :image,:image_cache)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :force_top, only: :show
  before_action :set_user, only: %i[show edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: 'ユーザー登録完了しました'
    else
      render 'new'
    end
  end

  def show
    @posts = @user.posts.limit(5).order('id DESC')
    @born_from = Time.zone.today - @user.birthday
  end

  def edit; end

  def update
    if @user.update(user_edit_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'ユーザー情報を削除しました'
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :email, :password, :child_name, :comment, :birthday,
      :image, :image_cache
    )
  end

  def user_edit_params
    params.require(:user).permit(
      :name, :email, :child_name, :comment, :birthday, :image, :image_cache
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/bord_comments_helper.rb
module BordCommentsHelper
end

app/helpers/circle_members_helper.rb
module CircleMembersHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_posts_helper.rb
module FavoritePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/trouble_bords_helper.rb
module TroubleBordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/_form.html.erb
<div class="mb-5">
  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circle.errors.count, "error") %></h2>
      <ul class="list-unstyled">
        <% @circle.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<%= form_with(model: @circle, local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :circle_name, class:"control-label col-2" %>
    <div class="col-8"><%= f.text_field :circle_name, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :circle_content, class:"control-label col-2" %>
    <div class="col-8"><%= f.text_area :circle_content, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <%= f.label :circle_image, class:"control-label col-2" %>
    <div class="col-8"><%= f.file_field :circle_image, id: :circle_image, class: "form-control-file" %></div>
      <%= f.hidden_field :circle_image_cache %>
  </div>
  <div class="form-group row text-center">
    <div class="offset-2 pl-3">
      <%= f.submit %>
    </div>
  </div>
<% end %>
<%= link_to "マイページに戻る", user_path(current_user.id), class: "btn btn-primary btn-lg rounded-pill mb-5" %>

app/views/circles/edit.html.erb
<div class="container text-center text-primary">
  <h2>サークル編集</h2>
  <%= render 'form' %>
</div>

app/views/circles/index.html.erb
<section class="portfolio bg-secondary" id="portfolio">
  <div class="container">
    <h2 class="text-center text-primary mb-2">サークル一覧</h2>
    <%= search_form_for @search do |f| %>
      <div class="input-group">
        <!-- <%= f.label :circle_name_or_circle_members_user_name_cont, "検索します" %> -->
        <%= f.text_field :circle_name_or_circle_members_user_name_cont, class: "form-controll" %>

        <div class="input-group-btn"><%= button_tag '<i class="fa fa-search"></i>検索'.html_safe, type: "submit", class: "btn btn-default btn-s-md" %></div>
      </div>
    <% end %>

    <% if @search_circles.empty? %>
      <div><%= "検索結果はありませんでした" %></div>
      <div><%= link_to "サークル一覧を表示する", circles_path %></div>
    <% end %>
    <div class="row">
      <% @circles.each do |circle| %>
        <div class="col-md-6 col-lg-4">
          <div class="post-grid">
            <%= link_to circle_path(circle.id) do %>
            <p><%= circle.circle_name %></p>
            <p><%= circle.circle_content %></p>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
      <div class="text-center"><%= link_to "新規サークル作成", new_circle_path, class: "btn btn-primary btn-lg rounded-pill" %></div>

  </div>
</section>

app/views/circles/new.html.erb
<div class="container text-center text-primary">
  <h2>サークル新規作成</h2>
  <%= render 'form' %>
</div>

app/views/circles/show.html.erb
<div class="portfolio-modal">
  <div class="portfolio-modal-dialog bg-secondary">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-primary mb-0">
            <%= @circle.circle_name %>
          </h2>
          <%= image_tag @circle.circle_image %>
          <hr class="star-dark">
          <p>サークルコメント</p>
          <h3 class="text-primary mb-5">
            <%= @circle.circle_content %>
          </h3>
          <hr class="star-dark">
          <p>サークルメンバー一覧</p>
            <% @circle.circle_members.each do |circlemember| %>
              <p class="mb-5"><%= link_to circlemember.user.name, user_path(circlemember.user.id) %></p>
            <% end %>
            <hr class="star-dark">
            <div class="text-center mb-5">
              <% if @circlemember.present? %>
              <% if current_user.id != @circle.user_id %>
                <%= link_to "サークルをやめます", circle_member_path(circle_id: @circle.id), method: :delete,class: "btn btn-danger btn-lg rounded-pill"  %>
              <% end %>
            <% else %>
              <%= link_to "サークルに参加する", circle_members_path(circle_id: @circle.id), method: :post, class: "btn btn-primary btn-lg rounded-pill"  %>
            <% end %>

            <% if current_user.id == @circle.user_id %>
              <%= link_to "サークル内容を変更する", edit_circle_path(@circle.id),class: "btn btn-primary btn-lg rounded-pill"  %>
              <%= link_to "サークルを削除する",circle_path(@circle.id),method: :delete, data: { confirm: '本当に削除していいですか？' },class: "btn btn-danger btn-lg rounded-pill"  %>
            <% end %>
          </div>
        </div>
      </div>
      <p class="mb-1"><%= link_to "サークル一覧に戻る", circles_path, class: "btn btn-primary btn-lg rounded-pill"  %></p>
    </div>
  </div>
</div>