config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  resources :posts do
    resources :comments
  end
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :circles
  resources :trouble_bords, only: %i[index create show destroy] do
    resources :bord_comments, only: %i[create edit update destroy]
  end
  resources :favorite_posts, only: %i[create destroy]
  resources :favorite_users, only: %i[create destroy]
  resources :circle_members, only: %i[create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bord_comment.rb
class BordComment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :trouble_bord
end

app/models/circle.rb
class Circle < ApplicationRecord
  validates :circle_name, presence: true
  has_many :circle_members, dependent: :destroy
  has_many :user, through: :circle_members
  mount_uploader :circle_image, ImageUploader
end

app/models/circle_member.rb
class CircleMember < ApplicationRecord
  belongs_to :user
  belongs_to :circle
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite_user.rb
class FavoriteUser < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorite_posts, dependent: :destroy
  has_many :followers, through: :favorite_posts, source: :user
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: :user
  mount_uploader :image, ImageUploader
end

app/models/trouble_bord.rb
class TroubleBord < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  has_many :bord_comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 } , on: :create
  before_save { email.downcase! }

  has_many :posts, dependent: :destroy
  has_many :trouble_bords, dependent: :destroy
  has_many :bord_comments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :circles, dependent: :destroy

  has_many :favorite_posts, dependent: :destroy
  has_many :favorite_another_posts, through: :favorite_posts, source: :post

  has_many :circle_members, dependent: :destroy
  has_many :favorite_circles, through: :circle_members, source: :circle

  has_many :active_favorite_users, foreign_key: 'follower_id',
            class_name: 'FavoriteUser', dependent: :destroy
  has_many :passive_favorite_users, foreign_key: 'followed_id',
            class_name: 'FavoriteUser', dependent: :destroy
  has_many :following, through: :active_favorite_users, source: :followed
  has_many :followers, through: :passive_favorite_users, source: :follower
  mount_uploader :image, ImageUploader

  def follow!(other_user)
    active_favorite_users.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_favorite_users.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_favorite_users.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :force_top

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post.id), notice: '日記を作成しました'
      unless @post.user.followers.blank?
        NoticeMailer.notice_mail(@post).deliver
      end
    else
      render 'new'
    end
  end

  def show
    @favorite_post = current_user.favorite_posts.find_by(post_id: @post.id)
    @comment = @post.comments.build
    @comments = @post.comments.order(created_at: :asc)
  end

  def index
    @search = Post.search(params[:q])
    @search_posts = @search.result.includes(:user).page(params[:page])

    current_user_id = params[:id]

    if current_user_id.nil?
      if @search_posts.nil?
        @posts = Post.page(params[:page])
      else
        @posts = @search_posts
      end
    else
      @posts = Post.where(user_id: current_user_id).page(params[:page])
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: '日記を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(current_user.id), notice: 'ブログを削除しました！'
  end
  private
  def post_params
    params.require(:post).permit(:title, :content, :image,:image_cache)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :force_top, only: :show
  before_action :set_user, only: %i[show edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: 'ユーザー登録完了しました'
    else
      render 'new'
    end
  end

  def show
    @posts = @user.posts.limit(5).order('id DESC')
    @born_from = Time.zone.today - @user.birthday
  end

  def edit; end

  def update
    if @user.update(user_edit_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'ユーザー情報を削除しました'
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :email, :password, :child_name, :comment, :birthday,
      :image, :image_cache
    )
  end

  def user_edit_params
    params.require(:user).permit(
      :name, :email, :child_name, :comment, :birthday, :image, :image_cache
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/bord_comments_helper.rb
module BordCommentsHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/trouble_bords_helper.rb
module TroubleBordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChildDiary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="#">
          <% if logged_in? %>
            <%= "こんにちは!! #{current_user.name}さん" %>
          <% else %>
            <%= "ようこそ！！Child_Diaryへ！！" %>
          <% end %>
        </a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "日記一覧", posts_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "サークル一覧", circles_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "マイ画面へ", user_path(current_user.id), class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "掲示板一覧", trouble_bords_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "ログアウト", session_path(current_user.id), method: :delete, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>

            <% else %>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "ログイン", new_session_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "新規ユーザー登録", new_user_path, class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <header class="masthead bg-primary text-white text-center">

      <div class="container mb-5">
        <h1 class="mb-0">Child Diary</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">ママと子供の成長日記へようこそ</h2>
        <h2 class="font-weight-light mb-0">子育てママを応援します！！</h2>
      </div>
        <% flash.each do |key, value| %>
          <h1><%= content_tag(:div, value, class: "#{key} text-primover") %></h1>
        <% end %>
    </header>
    <%= yield %>
    <footer>
      <div class="copyright py-4 text-center text-white">
        <div class="container">
          <small>Copyright &copy; KensukeMatsumoto 2018</small>
        </div>
      </div>
    </footer>
  </body>
</html>